input {
  tcp {
    port => 5001
    codec => json_lines
  }
}

filter {
  date {
    match => ["process_start_time", "MMM dd, yyyy '@' HH:mm:ss.SSS"]
    target => "process_start_time"
    timezone => "Africa/Dakar"
  }
  date {
    match => ["process_end_time", "MMM dd, yyyy '@' HH:mm:ss.SSS"]
    target => "process_end_time"
    timezone => "Africa/Dakar"
  }
  if [process_start_time] and [process_end_time] {
    ruby {
      code => "
        start = event.get('process_start_time').to_f
        stop  = event.get('process_end_time').to_f
        event.set('processing_duration_ms', ((stop - start) * 1000).round(2))
      "
    }
  }
  if [destination] == "toECS" {
    mutate { add_field => { "event_type" => "REJECT" } }
  } else if [source] == "RoutingPGW" or [source] == "E4_ROUTING" {
    mutate { add_field => { "event_type" => "ROUTE" } }
  } else {
    mutate { add_field => { "event_type" => "PROCESS" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
  }
}
