input {
  # mz_fixe_db - audit_markov_event_proc
  jdbc {
    id => "mz_fixe_db_proc"
    jdbc_connection_string => "jdbc:postgresql://10.137.19.69:5432/sonatel_audit"
    jdbc_user => "mzaudit"
    jdbc_password => "S0n@telMZ2023"
    jdbc_driver_library => "C:/Users/stg_sagne85105/OneDrive - Orange Sonatel/Documents/STAGE/markov_audit/postgresql-42.7.9.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    
    statement => "SELECT * FROM audit_markov_event_proc WHERE process_start_time > :sql_last_value"
    
    use_column_value => true
    tracking_column => "process_start_time"
    tracking_column_type => "timestamp"
    
    schedule => "*/5 * * * *"
    last_run_metadata_path => ".logstash_jdbc_mz_fixe_db_proc"
  }

  # mz_fixe_db - audit_markov_event_collect
  jdbc {
    id => "mz_fixe_db_collect"
    jdbc_connection_string => "jdbc:postgresql://10.137.19.69:5432/sonatel_audit"
    jdbc_user => "mzaudit"
    jdbc_password => "S0n@telMZ2023"
    jdbc_driver_library => "C:/Users/stg_sagne85105/OneDrive - Orange Sonatel/Documents/STAGE/markov_audit/postgresql-42.7.9.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    
    statement => "SELECT * FROM audit_markov_event_collect WHERE process_start_time > :sql_last_value"
    
    use_column_value => true
    tracking_column => "process_start_time"
    tracking_column_type => "timestamp"
    
    schedule => "*/5 * * * *"
    last_run_metadata_path => ".logstash_jdbc_mz_fixe_db_collect"
  }

  # mz_mobile_dev - audit_markov_event_proc
  jdbc {
    id => "mz_mobile_dev_proc"
    jdbc_connection_string => "jdbc:postgresql://10.137.19.42:5432/sonatel_audit"
    jdbc_user => "mzaudit"
    jdbc_password => "S0n@telMZ2023"
    jdbc_driver_library => "C:/Users/stg_sagne85105/OneDrive - Orange Sonatel/Documents/STAGE/markov_audit/postgresql-42.7.9.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    
    statement => "SELECT * FROM audit_markov_event_proc WHERE process_start_time > :sql_last_value"
    
    use_column_value => true
    tracking_column => "process_start_time"
    tracking_column_type => "timestamp"
    
    schedule => "*/5 * * * *"
    last_run_metadata_path => ".logstash_jdbc_mz_mobile_dev_proc"
  }

  # mz_mobile_dev - audit_markov_event_collect
  jdbc {
    id => "mz_mobile_dev_collect"
    jdbc_connection_string => "jdbc:postgresql://10.137.19.42:5432/sonatel_audit"
    jdbc_user => "mzaudit"
    jdbc_password => "S0n@telMZ2023"
    jdbc_driver_library => "C:/Users/stg_sagne85105/OneDrive - Orange Sonatel/Documents/STAGE/markov_audit/postgresql-42.7.9.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    
    statement => "SELECT * FROM audit_markov_event_collect WHERE process_start_time > :sql_last_value"
    
    use_column_value => true
    tracking_column => "process_start_time"
    tracking_column_type => "timestamp"
    
    schedule => "*/5 * * * *"
    last_run_metadata_path => ".logstash_jdbc_mz_mobile_dev_collect"
  }
}

filter {
  mutate {
    uppercase => [ "workflow_name" ]
    add_tag => [ "raw_audit" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "flux-audit-%{[@metadata][input_name]}-%{+YYYY.MM.dd}"
    document_id => "%{txn_id}"
  }
  stdout { codec => rubydebug }
}
